version: "2"

services:
  engine:
    image: qlikcore/engine:12.345.0
    restart: always
    command: -S AcceptEULA=yes -S DocumentDirectory=/data
    ports:
      - "19076:9076"
      - "19090:9090"
    volumes: 
      - ./data:/data
